.github/workflows/ci.yml
A test to run code generation per go module so we dont need to go work sync manually on every go module
=> chore: generate per module

.github/dependabot.yml
This makes sure we receive dependabot updates in our go bindings
=> chore: fixup dependabot config

Taskfile.yml
include prefixes are used in the test task to correctly run tasks. thats why the include must match the taskfile dir exactly. v2 was missing
=> fix: fixup task include

.github/workflows/ci.yml
Our CI matrix is dynamic so it cannot be used for required status checks in github. However we can add a failure step that can get triggered if any dependency fails or is cancelled. If this is the case, this job will fail. If CI is successful, the CI Completion Check will be skipped.
This will allow me to set `CI / Completion` as a required status check that I set in the github project settings
=> fix: introduce CI failure check

.env
see https://taskfile.dev/experiments/env-precedence/ on why. Basically makes sure that envs like GOBIN are respected if set in taskfiles and shell environment where task is run
=> fix: makes sure that we have env precedence enabled

.github/workflows/trigger-blackduck-scan.yaml
On-behalf-of: Gerald Morrison (SAP) <gerald.morrison@sap.com>
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
Calling the reusable Blackduck Scan actions fail with:
```
Invalid workflow file: .github/workflows/trigger-blackduck-scan.yaml#L22The workflow is not valid. .github/workflows/trigger-blackduck-scan.yaml (Line: 22, Col: 30): Unexpected value '3'
```  
e.g. https://github.com/open-component-model/open-component-model/actions/runs/14126917439
Therefore need to change parameter from string to number.
=> chore: correct parameter from string to number

bindings/go/runtime/raw_test.go, bindings/go/runtime/registry.go, bindings/go/runtime/registry_convert_test.go, bindings/go/runtime/registry_test.go, bindings/go/runtime/type.go, bindings/go/runtime/type_test.go, bindings/go/runtime/unstructured_test.go
It becomes evident that conversion logic centered around migrating from the old OCM Type system to the new type system is too big of a break. As such we will adopt the existing Type nomenclature of OCM which is completely untyped.
The effects of this will be:
- There is a context for ungrouped types that needs to be used (e.g. are you resolving an access type or an input type)
- Based on this knowledge, one has to use a correct well known registry.
- Based on this well-known registry, we can avoid conflicts with other ungrouped types based on other well-known registries.
=> fix!: remove grouped typings

bindings/go/runtime/registry.go, bindings/go/runtime/registry_convert_test.go, bindings/go/runtime/registry_test.go
this makes it so that if the scheme is set to allow unknown types, it will accept conversion from/to types that are not in the registry
=> feat: allow unknown conversions

bindings/go/dag/dag_test.go
cycle detection is not deterministic because of lack of order so there can be one of three combinations
=> fix: cycle detection test in dag

bindings/go/dag/go.mod
The dag module still had the incorrect module math, now that should be different due to a vanity
=> chore: fixup dag module path

bindings/go/dag/dag_test.go
fix failure as observed in [Details](https://github.com/open-component-model/open-component-model/actions/runs/14444482917/job/40501789190)
=> chore: fixup unstable test case because roots are not ordered by contract

bindings/go/oci/integration/integration_test.go, bindings/go/oci/internal/fetch/fetch.go, bindings/go/oci/internal/fetch/fetch_test.go, bindings/go/oci/internal/pack/pack.go, bindings/go/oci/repository.go, bindings/go/oci/repository_test.go, bindings/go/oci/store_descriptor.go
when we encounter single layer artifacts that we recognize as such, we can shortcut and fetch the only layer present instead of returning them as OCI image manifests
however if we do not encounter single layer artifacts we can just copy them as oci layouts instead.
makes sure the blob content when stored as single layer artifact is also received back as such. (see change in integration test)
also adds some tests for old component versions (like the old library implements)
=> fix: ensure that for single layer artifacts, we fetch the blob directly

bindings/go/oci/ctf/store.go, bindings/go/oci/internal/introspection/manifest.go, bindings/go/oci/internal/introspection/manifest_test.go, bindings/go/oci/internal/pack/pack.go, bindings/go/oci/internal/pack/pack_test.go, bindings/go/oci/repository.go, bindings/go/oci/tar/oci_layout_tar_writer.go, bindings/go/oci/tar/oci_layout_tar_writer_test.go
This makes it so that the global access is set to a layer if we have a non-manifest type, and an oci image if we do. This is because single layers are not full oci images so they should be references as oci image layers.
=> fix: make sure that manifests are discovered always and set global access

bindings/go/oci/internal/log/logging.go, bindings/go/oci/internal/log/logging_test.go, bindings/go/oci/repository.go, bindings/go/oci/store_descriptor.go
the oci Base and Operation logger were currently working incorrectly. The Base Logger didnt get updated when a new slog default logger was specified, and the Operation logger wrongly encapsulated the attributes causing double logged LEVELs and wrongly encoded messages.
I fixed this behavior and adjusted the test, which even checked for the incorrect value (my bad ...)
=> fix: oci logger formatting

bindings/go/credentials/spec/config/runtime/merge.go, bindings/go/credentials/spec/config/runtime/merge_test.go
previously empty configs resulted in a nil pointer (no configs present). this is undesirable. added a few tests as well
makes sure we dont panic when we dont have any cred configs!
=> fix: make sure merge works for empty configs

tools.Taskfile.yml
this parallelizes the lint execution so that each linter is run concurrently. Makes the lint significantly faster when run on the whole repo
=> chore: parallelize lint tasks when run on whole repo

bindings/go/plugin/client/sdk/plugin_test.go, bindings/go/plugin/manager/manager_test.go, bindings/go/plugin/manager/registries/componentversionrepository/registry_test.go
The problem was that all tests are using the same name and some didn't properly clean up the socket or the port or something and the next test wasn't able to run.
However, maybe I even need a way to overwrite the name of the socket. 🤔  Right now it's just generated from the name of the file.
=> fix: plugin manager test

bindings/go/runtime/registry.go, bindings/go/runtime/registry_test.go
This fixes up the registration order of typings to be deterministic so that only the first type registration causes a defaulting, whereas all following type definitions are aliases
=> fix: fixup non-deterministic registry behavior

bindings/go/plugin/client/sdk/plugin.go, bindings/go/plugin/client/sdk/plugin_test.go, bindings/go/plugin/internal/testplugin/main.go, bindings/go/plugin/manager/manager_test.go, bindings/go/plugin/manager/registries/componentversionrepository/endpoints_function_test.go, bindings/go/plugin/manager/registries/plugins/log_streamer.go, bindings/go/plugin/manager/registries/plugins/log_streamer_test.go
Keep log levels from plugins at the level that the plugin defined and relog them with a plugin ID on the level they defined.
Also, harden the log streamer so that if the plugin quits or the context is cancelled, the streaming attempts stop completely.
Closes https://github.com/open-component-model/ocm-project/issues/489
=> chore: add retaining log levels from plugins

bindings/go/blob/cache/inmemory/blob.go, bindings/go/blob/cache/inmemory/blob_test.go, bindings/go/blob/cache/inmemory/doc.go
see doc.go for details on usage (too long to maintain here)
This issue allows to wrap arbitrary blobs within an inmemory cache which is very useful whenever dealing with processing of data that has to read from it multiple times
=> feat: inmemory cached blobs

bindings/go/plugin/manager/manager_test.go
=> fix: flaky manager test sometimes removing something that is not there

renovate.json5
fixes up broken config settings to allow renovate runs again
=> chore: fixup renovate config

bindings/go/descriptor/normalisation/engine/jcs/normalise.go
fixes up a new lint issue that started with golangci v2
=> fix: fixup lint in jcs

bindings/go/descriptor/v2/go.mod, bindings/go/descriptor/v2/go.sum
=> chore: bump descriptor/v2 runtime to 0.0.1

.github/workflows/ci.yml
This fixes up the golang module generation so that integration tests are always run even if they themselves did not change, but their parent directory did. this is currently achieved with a simple linking from integration test module to owning parent module
=> fix: integration test trigger

.github/workflows/release-go-submodule.yaml
=> chore: dont use default suffix, so that not setting suffix is equal to no suffix

bindings/go/ctf/cas_file_blob.go, bindings/go/ctf/filesystem_ctf.go, bindings/go/ctf/filesystem_ctf_test.go, bindings/go/ctf/go.mod, bindings/go/ctf/go.sum, bindings/go/ctf/tar.go
this uses the recent leniency of the blob filesystem to allow any arbitrary go fs.FS implementation for use in CTFs
=> feat: allow creating CTFs from any fs.FS implementation

cli/cmd/setup.go, cli/go.mod, cli/go.sum, cli/internal/plugin/builtin/ctf/plugin.go, cli/internal/plugin/builtin/oci/plugin.go
In the Plugin Manager we can now use a dedicated error message to check this and only log a debug message instead of a warning.
=> fix: make it so that locations without plugins don't generate warning messages

bindings/go/blob/buffered_reader.go, bindings/go/blob/buffered_reader_test.go
this implements a default read / seek on the buffered reader so that everytime the buffer has been fully read, it gets reset fully and can be read from again.
This allows the following flow:
1. Read data from source (e.g. file) in memory
2. Read from memory after first read from file
3. Read again from memory henceforth (this was previously not possible)
part of https://github.com/open-component-model/ocm-project/issues/460
=> fix: implemented repeated read through ReadSeeker interface and automatic seek back

bindings/go/oci/doc.go, bindings/go/oci/integration/integration_test.go, bindings/go/oci/repository/provider/credential_cache.go, bindings/go/oci/repository/provider/credential_cache_test.go, bindings/go/oci/repository/provider/doc.go, bindings/go/oci/repository/provider/interface.go, bindings/go/oci/repository/provider/oci_cache.go, bindings/go/oci/repository/provider/provider.go, bindings/go/oci/repository/provider/provider_test.go, bindings/go/oci/repository/repository.go, bindings/go/oci/repository_options.go, bindings/go/oci/spec/credentials/identity/v1/type.go, bindings/go/oci/spec/credentials/identity/v1/type_test.go
In the current OCI lib there is no implementation that can switch based on the Type on which repository to create / resolve efficiently, leaving it up to users / the CLI.
This implementation provides an efficient and easy way to create component version repositories based on repository specifications.
This ultimately solves the problem of allowing an implementation that can be used for the plugin manager through the provider interface.
=> feat: component version repository provider

bindings/go/plugin/internal/testplugin-resource/main.go, bindings/go/plugin/manager/contracts/resource/v1/contracts.go, bindings/go/plugin/manager/contracts/resource/v1/types.go, bindings/go/plugin/manager/manager.go, bindings/go/plugin/manager/registries/resource/endpoints_function.go, bindings/go/plugin/manager/registries/resource/endpoints_function_test.go, bindings/go/plugin/manager/registries/resource/implementations.go, bindings/go/plugin/manager/registries/resource/implementations_test.go, bindings/go/plugin/manager/registries/resource/registry_test.go, bindings/go/plugin/manager/types/types.go
this corrects the resource contract so that we have the correct typings for global resource downloads
=> fix: correct resource contract

bindings/go/plugin/manager/contracts/resource/v1/types.go, bindings/go/plugin/manager/registries/resource/implementations.go
It doesnt make sense that the upload / add of a global resource does not expect a location of the blob data. we should change this
=> fix: move locataion ownership from response to request for adding resources

bindings/go/constructor/construct.go, bindings/go/constructor/construct_resource_test.go, bindings/go/constructor/construct_source_test.go, bindings/go/constructor/construct_test.go
currently the constructor conflict resolution strategy did not properly abort and return the conflicting descriptors, this has been fixed.
additionally, the consumer identity will now not cause a failing construction if construction is still possible without credentials (failed resolution of an identity is logged with debug)
=> fix: fixup conflict resolution strategy for component constructors

cli/cmd/get/component-version/cmd.go
Do we want to support all aliases `ocm get cv` used in the OCM CLI V1 (for compatibility reasons)? See also:
https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_get_componentversions.md
=> fix: support for aliases used in OCM CLI V1

bindings/go/constructor/construct.go, bindings/go/constructor/construct_callbacks_test.go, bindings/go/constructor/options.go
This adds optional lifecycle callbacks to the constructor 
```
type ComponentConstructionCallbacks struct {
// OnStartComponentConstruct is called before the construction of a component version starts.
OnStartComponentConstruct func(ctx context.Context, component *constructor.Component) error
// OnEndComponentConstruct is called after the construction of a component version ends.
// If an error occurs during the construction, the error is passed as a parameter.
OnEndComponentConstruct func(ctx context.Context, descriptor *descriptor.Descriptor, err error) error
// OnStartResourceConstruct is called before the construction of a resource starts.
OnStartResourceConstruct func(ctx context.Context, resource *constructor.Resource) error
// OnEndResourceConstruct is called after the construction …
```
=> feat: constructor callbacks

bindings/go/oci/integration/integration_test.go, bindings/go/oci/internal/lister/lister.go, bindings/go/oci/repository.go, bindings/go/oci/repository/repository.go, bindings/go/oci/repository_options.go, bindings/go/oci/resolver/url/options.go, bindings/go/oci/resolver/url/resolver.go, bindings/go/oci/resolver/url/resolver_test.go, bindings/go/oci/spec/index/component/v1/index.go, bindings/go/oci/store_descriptor.go
this makes the referrer index, the index creation, subject reference on the index, as well as the listing via referrer API optional and hidden behind a configurable policy that is by default disabled. (this is the expected behavior if moving from a legacy OCM repository, as we didnt have referrer support before)
=> feat!: make referrer indexes and lookup optional and disable by default

bindings/go/descriptor/v2/descriptor.go, bindings/go/descriptor/v2/descriptor_test.go
this is the removal of the size attribute in the resource, which we prototyped with extensively. however resource sizes are not feasible for a lot of types and should rather be access-specific.
=> fix!: size was originally never an attribute, lets remove it

bindings/go/oci/ctf/store.go, bindings/go/oci/ctf/store_test.go, bindings/go/oci/integration/integration_test.go, bindings/go/oci/interface.go, bindings/go/oci/internal/digest/digest.go, bindings/go/oci/repository.go, bindings/go/oci/repository_test.go
add a method / interface that allows us to process and append / pin digests to resources backed by OCI Images efficiently via resolve calls.
This allows the component constructor to efficiently construct OCI based blob digests.
=> feat: introduce oci backed resource digest processor

bindings/go/oci/internal/lister/component/component_versions.go, bindings/go/oci/internal/lister/component/component_versions_test.go, bindings/go/oci/internal/lister/lister.go, bindings/go/oci/repository.go, bindings/go/oci/spec/annotations/annotations.go, bindings/go/oci/spec/annotations/annotations_test.go
previously the lib only used the tags resolve functionality when listing tags. this could cause issues if there were other tagged manifests that were not ocm component versions. also the tagging was not properly concurrent but worked in concurrent blocks equivalent to the tag list page size.
now tag listing works concurrently based on the resolution of the manifest and then the interpretation of the component version annotation on the manifest to differentiate OCM and non OCM versions. While less efficient (a fetch call more per tag), due to the efficiency gains during listing, we should still be good to go.
TLDR: 
- Now we can concurrently fetch all tags, and not just all tags in a page from OCI
- The tag listing actually introspects the discovered tagged manifests, and filters any that …
=> fix: proper tag listing

bindings/go/oci/internal/pack/pack.go, bindings/go/oci/internal/pack/pack_test.go, bindings/go/oci/repository.go, bindings/go/oci/repository_options.go, bindings/go/oci/repository_test.go
because we only use the runtime package in OCI repositories, we shouldn't need to deal with crazy raw to type conversions. Instead any caller should have preconverted types that we assert on. This means that effectively one has to already use the correct access type and not just Raw to use the lib. This makes the coding easier to handle.
=> chore!: make sure that OCI lib expects only already converted accesses

.github/config/linkspector.yaml, .github/config/markdown-link-check.json, .github/workflows/markdown.yml
current link checker is deprecated and replaced with linkspector.
=> chore(ci): replace link checker

bindings/go/plugin/manager/registries/resource/contract.go, bindings/go/plugin/manager/registries/resource/registry_test.go, bindings/go/plugin/manager/registries/resource/resource_converter.go
for resource repositories, we were using the constructor runtime for consumer identity resolution, but this was the wrong interface. instead we should use the descriptor runtime.
=> fix: make sure to not use constructors in resource repositories

bindings/go/descriptor/v2/descriptor.go, bindings/go/descriptor/v2/descriptor_test.go
The ocm specifies that the version property is optional (see https://github.com/open-component-model/ocm-spec/blob/main/doc/01-model/03-elements-sub.md#element-identity).
=> fix: adjust to identity to omit empty name and/or version

.github/workflows/renovate.yml
lets try to no proxy our modules so we dont rely on the go proxy cache to hold our digest updates which can confuse renovate
=> chore(ci): try to force monorepo updates directly from VCS

.github/config/renovate.json5
allowing the env is needed for self hosted renovate
=> chore(ci): try to force monorepo updates via proxy api

.github/workflows/openssf-scorecard.yml
Due to https://github.com/ossf/scorecard-action?tab=readme-ov-file#workflow-restrictions we cannot inject our usual github bot token so we run without the branch protection check
=> chore(ci): make sure that sarif scan is allowed and does not use OCM token

bindings/go/oci/internal/fetch/fetch.go, bindings/go/oci/internal/fetch/fetch_test.go, bindings/go/oci/repository_test.go
In ocm v1, the version - even if given - is omitted from the identity if the identity is already unique without the version.
In ocm v2, the version is always part of the identity.
Within oci, the identity of resources and sources is written as an layer annotation. ocm v2 leverages this annotation to filter for the correct layer(s) of a resource. Due to above behavior, in case the version is given but is not required for the identity to be unique, the identities were not **equal** and thus, the layer were not found.
To fix this, this PR exchanges the **equality** matcher with a **subset** matcher. Since `(identity) is subset of (identity + version)`, the layers can now be found.
=> fix(oci): adjust oci to be able to deal ocm v1 oci manifests of ocm components

bindings/go/repositories/componentrepository/fallback/v1/repository.go, bindings/go/repositories/componentrepository/interface.go
Instead of defining an error type, we decided, we'd rather join the errors and check for the error using `errors.Is`.
=> feat(repositories): switch from error type to error instance for easier error checks

bindings/go/oci/repository.go
we currently use the wrong method to inject a new logger into the context
=> fix: make sure that the correct method is used for slogcontext

cli/cmd/setup_filesystem_config.go, cli/cmd/setup_test.go
The flag wasn't taken correctly and it was always outputting an error.
=> fix: set the temp folder flag on change

bindings/go/ctf/filesystem_ctf.go, bindings/go/ctf/filesystem_ctf_test.go
previously the ctf file writing was not truncated which led to cases where files that were written had trailing data which was invalid
=> fix(ctf): make sure that index is truncated

.github/workflows/cli.yml
this makes it so that the CTF build now uses cached values from the CLI go.mod so that it becomes faster and we dont have to maintain a separate go.mod. It does this by checking out the CLI first
=> chore(ci): make CLI CTF build faster by caching the CLI go dependencies

cli/go.mod, cli/go.sum, cli/internal/plugin/builtin/builtin.go, cli/internal/plugin/builtin/input/dir/method.go
This PR adds the `dir` input method to the CLI. I.e. when merged, it will be possible to do `ocm add cv` command with `--constructor` flag pointing to a `component-constructor.yaml`, which has a resource with an `input` of type `dir`.
Supported scope:
* Absolute paths or paths relative to the working directory in the `path` filed
* Uncompressed input (`compress` field omitted or set to false)
Out of scope:
* Paths relative to component constructor (open-component-model/ocm-project#565)
* `compress: true` (open-component-model/ocm-project#566)
=> feat: add `dir` input to cli

bindings/go/descriptor/runtime/convert_v2.go
adds 2 nil checks that were missing for resource conversion when passed a nil resource to avoid panic when calling with nil
part of the helm input binary test did with @Skarlso 
part of https://github.com/open-component-model/ocm-project/issues/490
=> fix: handle nil resources in descriptor runtime conversion functions

bindings/go/plugin/client/sdk/plugin.go, bindings/go/plugin/manager/manager.go, bindings/go/plugin/manager/manager_test.go, bindings/go/plugin/manager/registries/input/registry.go, bindings/go/plugin/manager/registries/input/resource_input_converter.go, bindings/go/plugin/manager/registries/plugins/log_streamer.go
- Add proper signal handling for graceful plugin shutdown.
- Fix context usage for server shutdown timeout.
- Log additional shutdown details and handle server close errors.
- Extend plugin manager's shutdown handling to include:
- CredentialRepositoryRegistry
- InputRegistry
- DigestProcessorRegistry
- ResourcePluginRegistry
- BlobTransformerRegistry
- Improve error aggregation during shutdown.
- Use `errgroup` for concurrent plugin shutdown.
- Add proper error handling during shutdown, including `os.Interrupt` and process waiting.
- Use `context.Done()` to handle timeout scenarios, killing process if ctx is killed
- Remove unnecessary intermediate steps during v2 resource conversion.
- Use direct conversion to streamline the process.
- Add check for channel closure when receiving errors …
=> fix: manager plugin lifecycle handling

bindings/go/dag/sync/traverse.go
This PR sets the state discovering reliably even if the root already exists in the graph.
=> fix(dag): traversal state discovering was not set if root was determined from graph

bindings/go/configuration/filesystem/v1alpha1/spec/config.go, bindings/go/configuration/scheme.go, bindings/go/configuration/scheme_test.go
- Implemented a global `Scheme` in the configuration package.
- Refactored `filesystem` configuration to use the global `Scheme`.
- Added a unified `Register` function for managing scheme registrations across sub-packages.
- Introduced tests to validate registration functionality.
This enables a centralized management of runtime schemes and simplifies scheme integration in the codebase.
=> feat(configuration): introduce global scheme and improve registration handling

bindings/go/input/dir/blob.go, bindings/go/input/dir/go.mod, bindings/go/input/dir/go.sum
Currently, the monorepo upgrade job is blocked because of a test failure in the dir input methods. This PR resolves the test failure and manually upgrades the blob dependency of the dir input method to work towards unblocking the monorepo upgrade job.
This is the change in the blob module that broke the current behaviour:
```
- func (s *osFileSystem) ReadDir(name string) ([]fs.DirEntry, error) {
-	return os.ReadDir(filepath.Join(s.base, name))
+ func (s *RootFileSystem) ReadDir(name string) ([]fs.DirEntry, error) {
+	return s.root.FS().(fs.ReadDirFS).ReadDir(name)
```
With the original variant, `name == ""` resulted in a valid path due to `filepath.Join(s.base, name)`. With the new variant, we call `rootFS.ReadDir(name)` which internally calls `fs.ValidPath(name)`. `fs.ValidPath(name)` …
=> fix: manually update blob dependency to unblock monorepo job

.github/workflows/kubernetes-controller.yml, kubernetes/controller/Dockerfile, kubernetes/controller/Taskfile.yml
When we push our image, which is multi-arch, we cannot use a "loaded" version from the docker daemon we use for e2e testing, because that doesn't support multi-arch. That means we need to push directly from the builder instance instead of loading it first.
Fixes https://github.com/open-component-model/open-component-model/actions/runs/17262857226/job/48988854136
=> fix(ci): streamline docker build and push process for multi-architecture support

.github/workflows/kubernetes-controller.yml
makes sure that instead of regular docker we use buildx which supports multi-arch envs
fix https://github.com/open-component-model/open-component-model/actions/runs/17266023272/job/48998912995
=> chore: attempt multi-arch-fix

.github/workflows/kubernetes-controller.yml
adds a manual dispatch trigger in case we want to run k8s controller workflows again without the controller having changed
=> chore: add dispatch trigger to k8s workflow

.github/workflows/renovate.yml
- Introduced `RENOVATE_REPOSITORIES` variable to `renovate.yml`.
- Properly triggers renovate
=> chore: add support for repository-specific Renovate environment variable

.github/workflows/renovate.yml
- Introduced repository caching mechanisms for Renovate to improve performance.
- Added new `workflow_dispatch` input parameter `repoCache` to control caching behavior (enabled, disabled, or reset).
- Included steps to restore, compress, and upload cache artifacts.
- Updated Renovate configuration to utilize cache directory.
This update optimizes Renovate runs and provides greater flexibility for manual dispatch scenarios.
=> chore: enhance Renovate workflow with caching and dispatch inputs

.github/config/renovate.json5, renovate.json5
Turns out neither of the defaults or extends are dealing with groupping go modules related to docker repositories. I looked at extends, group defaults, recommended and default grouppings. Looked for extendable docker configs and presets. They mostly deal with Dockerfile image versions actually. And not go modules.
=> chore: group docker package updates into a single pull request

bindings/go/dag/sync/conversion_test.go, bindings/go/dag/sync/dag.go, bindings/go/dag/sync/discover.go, bindings/go/dag/sync/discover_test.go, bindings/go/dag/sync/process.go, bindings/go/dag/sync/process_test.go, bindings/go/dag/sync/traverse.go, bindings/go/dag/sync/traverse_test.go
This PR introduces logic to perform concurrent topological traversal of a dag, with child nodes always being processed before its parent node.
- It also fixes a "bug" in the `Reverse` methods where attributes have not been copied (it was simply not implemented).
- It renames `Traverse` to `Discover` since this caused a lot of confusion.
- It fixes a flaw in the `Discover`/`DiscoverNeighbors` logic that allowed the discover neighbors function to add attributes to the neighbors which had the potential to cause races. Now, the discover neighbors logic is only passed the vertex ID and can only return the neighbor vertices IDs. 
- This is sufficient for our component cases for now. If we need attributes during discovery in the future, we'd have to add them to the edges.
Contributes to: …
=> feat(dag)!: introduce dag processing logic

renovate.json5
- Added a new Renovate configuration group for `google.golang.org/{/,}**` packages.
- Helps reduce PR clutter by bundling updates related to Google Golang repositories.
- Improves dependency update management for Google-related Golang packages.
=> chore(renovate): group Google Golang repositories

.github/workflows/renovate.yml
- Updated `RENOVATE_DRY_RUN` environment variable in `.github/workflows/renovate.yml` to trigger dry runs for pull requests and disable it for other events.
- Ensures proper validation of Renovate changes on relevant PRs.
=> chore(renovate): update dry-run condition in GitHub workflow

.github/workflows/renovate.yml
- Removed inline `RENOVATE_DRY_RUN` definition from the environment section.
- Added a new step to explicitly set `RENOVATE_DRY_RUN` to `extract` for pull requests.
- Improves clarity and maintainability of the workflow file by isolating the dry-run configuration.
Addresses feedback to make the workflow configuration cleaner and more explicit.
=> chore(renovate): move dry-run setup to a dedicated step in workflow

bindings/go/plugin/manager/registries/componentversionrepository/registry.go, bindings/go/plugin/manager/registries/componentversionrepository/registry_test.go
Added internal plugin credential identity support for provider that was accidentally left out
follow up to https://github.com/open-component-model/open-component-model/pull/790
=> fix(registry): add credential identity support for internal plugins

bindings/go/dag/dag.go, bindings/go/dag/dag_test.go, bindings/go/dag/sync/conversion_test.go, bindings/go/dag/sync/dag.go, bindings/go/dag/sync/discover.go, bindings/go/dag/sync/map_to_synced.go, bindings/go/dag/sync/process.go, bindings/go/dag/sync/synced_to_map.go
fixes a nil pointer and a data race that could occur on vertex retrieval
=> fix(dag): fix various races

cli/internal/reference/compref/compref.go, cli/internal/reference/compref/compref_test.go
Previously, repository references in the format of IP:PORT were incorrectly recognised due to a parsing error. This fix ensures that repositories behind an IP address are correctly detected.
Fixes https://github.com/open-component-model/ocm-project/issues/651
=> fix(oci): fix repository detection for OCI URLs with IP addresses

bindings/go/rsa/signing/v1alpha1/config.go
The default signature encoding policy was wrongly hard coded to PEM which caused empty Configs to incorrectly default to PEM even though the default is Plain
uses the default constant as originally intended
=> fix(rsa): update default signature encoding policy to SignatureEncodingPolicyDefault

.github/workflows/ci.yml
if we dont do this the output of the modules will be prefixed as our other tasks so it will not be possible to parse it just by new line.
=> fix(ci): update go_modules task to use interleaved output

cli/cmd/cmd_test.go, cli/cmd/get/component-version/cmd.go, cli/internal/render/graph/tree/renderer.go, cli/internal/render/graph/tree/renderer_options.go, cli/internal/render/graph/tree/renderer_test.go, cli/internal/render/graph/tree/serializer.go, cli/internal/render/graph/tree/serializer_options.go, cli/internal/render/graph/tree/style.go
This change refactored the tree renderer to use a column-aware output format (NESTING, COMPONENT, VERSION, PROVIDER, IDENTITY) combined with the visual tree hierarchy.
```shell
$ ocm cv ... -o tree
NESTING  COMPONENT            VERSION  PROVIDER      IDENTITY                               
├─ ●     ocm.software/root    0.0.2    ocm.software  name=ocm.software/root,version=0.0.2   
│  └─    ocm.software/leaf-a  0.0.1    ocm.software  name=ocm.software/leaf-a,version=0.0.1 
└─ ●     ocm.software/root    0.0.1    ocm.software  name=ocm.software/root,version=0.0.1   
├─    ocm.software/leaf-a  0.0.1    ocm.software  name=ocm.software/leaf-a,version=0.0.1 
└─    ocm.software/leaf-b  0.0.1    ocm.software  name=ocm.software/leaf-b,version=0.0.1
``` 
Fixes …
=> chore: columnar output combined with the visual tree hierarchy

.github/renovate.json5
this reduces the amount of branch creations we receive as main update will only update branches and not create new PRs.
Fresh PRs / new updates are *created once per week*.
Existing PRs / old updates (not yet merged) are *updated automatically on every commit*
Also automerge is now enabled for all PRs as we have had good experience with it (still approval is required)
=> fix(renovate): update schedule and minimum release age settings and fixup automerge
