open-component-model/open-component-model

.github/workflows/codeql.yml

makes sure the codeql check runs on our go modules

chore: fixing up codeql

---

bindings/go/runtime/go.mod
bindings/go/runtime/type_test.go

fix: package name from golang to go

---

Taskfile.yml

fix: Taskfile pointing to an incorrect location

---

.github/dependabot.yml

On-behalf-of: Gerald Morrison (SAP) <gerald.morrison@sap.com>
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
change dependabot schedule for actions to daily

chore: change Dependabot update schedule from weekly to daily

---

bindings/go/runtime/registry.go
bindings/go/runtime/registry_test.go

this adds a convenience method for defaulting the type of a typed object that is potentially not set on a type.
it also fixes a bug in decoding in which it could be that an object was decoded when unknown types were allowed in which the target type mismatches the expected type, which should be caught

fix: defaulting of types and decoding

---

bindings/go/descriptor/runtime/artifact.go

this introduces the artifact interface. A commond interface through which one can jointly program logic against both Sources and Resources. Makes it much easier to program component version repositories for joint logics.

feat: artifact interface

---

bindings/go/plugin/internal/testplugin/main.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/contracts.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/types.go
bindings/go/plugin/manager/registries/componentversionrepository/endpoints_function.go
bindings/go/plugin/manager/registries/componentversionrepository/endpoints_function_test.go
bindings/go/plugin/manager/registries/componentversionrepository/handlers.go
bindings/go/plugin/manager/registries/componentversionrepository/implementations.go
bindings/go/plugin/manager/registries/componentversionrepository/implementations_test.go
bindings/go/plugin/manager/registries/componentversionrepository/typed_conversion.go

feat: add list component version

---

bindings/go/plugin/manager/manager.go

feat: return a specific error when there are no plugins

---

bindings/go/blob/cache/inmemory/blob.go
bindings/go/blob/cache/inmemory/blob_test.go

in case a cached blob did not already cache data and its underlying source blob also doesn't offer a sizing information, the cached blob can now dynamically load the data and use the cached content to determine the size.
Makes sure that a cached blob always has sizing information available to it, because loading the data would always report a valid size

feat: hot load size in cached blob

---

bindings/go/plugin/manager/registries/plugins/log_streamer.go
bindings/go/plugin/manager/registries/plugins/log_streamer_test.go

fix: sort the incoming keys from the log output

---

bindings/go/credentials/graph.go
bindings/go/credentials/ingest.go
tools.Taskfile.yml

fixes up our task for linting and the last findings in credentials

fix: fixup lint install run and cred run

---

bindings/go/oci/ctf/store.go
bindings/go/oci/internal/lister/component/component_versions.go
bindings/go/oci/repository.go
cli/internal/plugin/builtin/ctf/plugin.go
cli/internal/plugin/builtin/oci/plugin.go
tools.Taskfile.yml

further fixes up findings in the golang ci runner

fix: fixup golangci v2 run

---

.github/config/release.yaml

introduces a github action for submodule releases to start stabilizing our API

chore: setup submodule releases

---

bindings/go/configuration/v1/go.mod

fix: go module package name to ocm.software

---

.github/workflows/release-go-submodule.yaml

chore: remove automatic bump, default to dry run, and allow suffix

---

.github/workflows/release-go-submodule.yaml

chore: support major version suffixes in mod paths

---

.github/workflows/release-go-submodule.yaml

chore: fixup submodule release

---

bindings/go/descriptor/runtime/go.mod
bindings/go/descriptor/runtime/go.sum

chore: pin descriptor v2 in descriptor runtime

---

bindings/go/plugin/internal/testplugin/main.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/contracts.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/types.go
bindings/go/plugin/manager/manager_test.go
bindings/go/plugin/manager/registries/componentversionrepository/endpoints_function_test.go
bindings/go/plugin/manager/registries/componentversionrepository/handlers.go
bindings/go/plugin/manager/registries/componentversionrepository/handlers_test.go
bindings/go/plugin/manager/registries/componentversionrepository/implementations.go
bindings/go/plugin/manager/registries/componentversionrepository/implementations_test.go
bindings/go/plugin/manager/registries/componentversionrepository/registry.go
bindings/go/plugin/manager/registries/componentversionrepository/typed_conversion.go

chore: add get local resource response

---

bindings/go/runtime/registry.go
bindings/go/runtime/registry_test.go

this adds functions for
- copying all types or specific types from one scheme to another
- getting all existing types from the registry
This is useful if one works with multiple schemes and one scheme works as an aggregation of 
This also removes a leftover where there could be versioned and non versioned defaults. since this was removed, we can remove the code path for the preference of the versioned default.

feat: allow access to all registered types in the scheme

---

bindings/go/plugin/manager/registries/digestprocessor/registry.go

the digest processor registry used a lookup by prototype which is not safe as a prototype can be associated with many types. As such the gePlugin call sometimes failed for internal plugins which are registered by type string and not by prototype.

fix: correct lookup for digest processor plugins

---

bindings/go/constructor/construct_test.go

Closes https://github.com/open-component-model/open-component-model/issues/269

fix: the mock was causing concurrent map access

---

bindings/go/plugin/manager/registries/componentversionrepository/handlers.go

fix: remove this todo because the type is passed in

---

cli/cmd/generate/cmd.go
tools.Taskfile.yml

fix: concurrent intermediary step to ensure we install once and then run concurrently

---

.github/config/renovate.json5
.github/workflows/renovate.yml

attempt to fixup the self hosted setup

fix(ci): renovate self hosted

---

bindings/go/oci/ctf/store.go
bindings/go/oci/ctf/store_test.go
bindings/go/oci/go.mod
bindings/go/oci/go.sum
bindings/go/oci/integration/go.mod
bindings/go/oci/integration/go.sum
bindings/go/oci/interface.go
bindings/go/oci/internal/lister/lister.go
bindings/go/oci/internal/log/logging.go
bindings/go/oci/repository.go
bindings/go/oci/repository_options.go
bindings/go/oci/repository_test.go
bindings/go/oci/resolver/url/resolver.go
bindings/go/oci/resolver/url/resolver_test.go
bindings/go/oci/semver_tag.go
bindings/go/oci/store_descriptor.go

feat: make the base logger configurable through context

---

.github/workflows/renovate.yml
tools.Taskfile.yml

chore(ci): try to force monorepo updates via proxy api

---

.github/config/wordlist.txt
docs/steering/meeting-notes/2025-08-04.md

Add agenda item to vote on TSC membership of @zkdev .

chore(docs): Add odg-representation agenda item

---

bindings/go/plugin/go.mod
bindings/go/plugin/go.sum
bindings/go/plugin/internal/testplugin-component-version/main.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/contracts.go
bindings/go/plugin/manager/contracts/ocmrepository/v1/types.go
bindings/go/plugin/manager/registries/componentversionrepository/endpoints_function_test.go
bindings/go/plugin/manager/registries/componentversionrepository/implementations.go
bindings/go/plugin/manager/registries/componentversionrepository/typed_conversion.go

Takes care of https://github.com/open-component-model/ocm-k8s-toolkit/issues/249#issuecomment-3072373059.

feat: update the plugin manager component version repository with CheckHealth

---

docs/steering/meeting-notes/2025-08-04.md
docs/steering/meeting-notes/2025-09-01.md

Adds results and agenda of TSC Meeting

chore(docs): OCM TSC Call

---

bindings/go/input/helm/blob.go

This PR is similar to #501. It does a similar fix, but in the helm input method.

fix: helm input: optimize OCI layout writing

---

tools.Taskfile.yml

fix: remove dependency on defer linting

---

docs/steering/meeting-notes/2025-09-01.md

chore(docs): add security officer election to next TSC meeting

---

.github/workflows/ci.yml
cli/cmd/add/component-version/cmd.go
cli/cmd/internal/cmd/flags.go
cli/docs/reference/ocm.md
cli/docs/reference/ocm_add.md
cli/docs/reference/ocm_add_component-version.md
cli/docs/reference/ocm_completion.md
cli/docs/reference/ocm_completion_bash.md
cli/docs/reference/ocm_completion_fish.md
cli/docs/reference/ocm_completion_powershell.md
cli/docs/reference/ocm_completion_zsh.md
cli/docs/reference/ocm_download.md
cli/docs/reference/ocm_download_plugin.md
cli/docs/reference/ocm_download_resource.md
cli/docs/reference/ocm_generate.md
cli/docs/reference/ocm_generate_docs.md
cli/docs/reference/ocm_get.md
cli/docs/reference/ocm_get_component-version.md
cli/docs/reference/ocm_version.md

we had a break in our generation workflow when we changed CI to pull request target. this should fix this

fix(ci): properly generate and add repo checkout to generate

---

.github/workflows/kubernetes-controller.yml

adds task to the image publishing job
fixes task not being available causing main controller image builds to fail in https://github.com/open-component-model/open-component-model/actions/runs/17241020227/job/48918950355

fix: make sure controller image is built correctly

---

.github/workflows/kubernetes-controller.yml

chore: attempt to overcome madness by passing repo

---

.github/workflows/kubernetes-controller.yml
kubernetes/controller/Taskfile.yml

tries to use the inbuilt token to leverage org package permissions for image push

chore: attempt to use inbuilt token

---

.github/workflows/latest.yml

chore: update latest.yml to manage checks for publishing controller image

---

.env
.github/config/renovate.json5
.github/workflows/ci.yml
kubernetes/controller/Taskfile.yml
kubernetes/controller/internal/controller/component/suite_test.go
kubernetes/controller/internal/controller/deployer/suite_test.go
kubernetes/controller/internal/controller/replication/suite_test.go
kubernetes/controller/internal/controller/repository/suite_test.go
kubernetes/controller/internal/controller/resource/suite_test.go
renovate.json5
tools.Taskfile.yml

- Introduced additional tool version definitions in `.env` to improve version management.
- Refined `Taskfile.yml` to ensure version consistency for tools such as `golangci-lint`.
- Updated `renovate.json5` files to support better automation, including custom datasources and regex managers.
- Removed redundant environment variables from `controller/Taskfile.yml` as they are now centrally managed.
- Simplified workflows in `ci.yml` to align with updated configuration.
These changes improve dependency tracking, tooling automation, and configuration clarity.

chore: enhance dependency configuration and tooling

---

bindings/go/plugin/manager/manager_test.go

Fixes run: https://github.com/open-component-model/open-component-model/actions/runs/17324612481/job/49185509647

fix: do not error out on removing a non-existant socket
